- README.md
Also serves as test for CI triggers
> Add status badge to Readme

- azure-pipelines.yml
Based on Arcade's azure-pipelines.yml
> remove osx and add publishing/signing jobs

- eng/validation/templates/testing/helix.yml
Tes build: https://dnceng.visualstudio.com/internal/_build/results?buildId=59803
> Refer execution of helix.yml to jobs.yml

- azure-pipelines.yml
Test build: https://dnceng.visualstudio.com/internal/_build/results?buildId=59862
> Enable publish to BAR task

- azure-pipelines.yml
- eng/validation/templates/signing/sign.yml
- eng/validation/templates/testing/helix.yml
- eng/validation/update-channel.ps1
> add final build job that updates the channel, and only runs if every other job succeeds

- azure-pipelines.yml
Re-enabling now that P2 shipped.
@markwilkie, @jcagme
> re-enable push to latest channel

- azure-pipelines.yml
Might as well try it and see if this unblocks dependency update prs.
> Use debian as workaround to core/eng#5209

- azure-pipelines.yml
fixes https://github.com/dotnet/arcade/issues/2411
> Move from temp pools to byoc

- azure-pipelines.yml
- global.json
* Move to use prod pool provider
* Use newer version of SDK to try and prevent NU3004 error
> update sdk to avoid nuget bug, and move to prod BYOC provider

- azure-pipelines.yml
Only moved the windows legs last time. Oops.
> move the linux build legs to the prod pool provider

- azure-pipelines.yml
Relates to: https://github.com/dotnet/arcade/issues/3016
> On-board with using YAML-based release pipelines

- azure-pipelines.yml
See here for reason: https://github.com/dotnet/arcade/issues/3069
> Disable SourceLink validation step

- global.json
> Move to 3.0 Preview 6 SDK and 2.1.11 runtime

- azure-pipelines.yml
Test Build - https://dev.azure.com/dnceng/internal/_build/results?buildId=243546&view=results
> Fix TsaRepoName and TsaCodebaseName

- eng/Version.Details.xml
- eng/common/init-tools-native.ps1
- eng/common/post-build/darc-gather-drop.ps1
- eng/common/templates/post-build/channels/internal-servicing.yml
- eng/common/templates/post-build/channels/public-dev-release.yml
- eng/common/templates/post-build/channels/public-release.yml
- eng/common/templates/post-build/channels/public-validation-release.yml
- eng/common/templates/post-build/darc-gather-drop.yml
- eng/common/templates/post-build/post-build.yml
- eng/common/templates/post-build/trigger-subscription.yml
- global.json
Subscription is not creating PRs. This is a manual update to see if we can unblock dependency flow of Arcade, which has a few critical fixes.
> Update Arcade dependencies

- .gitignore
- eng/common/tools.sh
- global.json
Fixes https://github.com/dotnet/arcade/issues/3370.
Builds failing as expected on powershell fix that hasn't flowed through yet.
> Add cmake and python native tools to test native tools scripts

- eng/common/enable-cross-org-publishing.ps1
Was already brought back by https://github.com/dotnet/arcade-validation/commit/f9f843041d144c74f79668e2fef1e762e983509f but deleted in the subsequent commit. cc @riarenas
> Re-add removed file

- NuGet.config
Test build: https://dev.azure.com/dnceng/internal/_build/results?buildId=374380
> Add the dotnet-tools feed for restores

- azure-pipelines.yml
Area Path in DevDiv changed for NET Core, updating the settings to change the same. 
Test Build - https://dev.azure.com/dnceng/internal/_build/results?buildId=397080&view=logs&s=6884a131-87da-5381-61f3-d7acc3b91d76&j=7d9eef18-6720-5c1f-4d30-89d7b76728e9
> Update AreaPath for SDL TSA Onboarding

- eng/common/SetupNugetSources.ps1
- eng/common/SetupNugetSources.sh
resurrected the files by running a `darc update-dependencies --channel ".NET Tools - Validation"`
> Add back scripts deleted by dependency update PR

- azure-pipelines.yml
Reaction to https://github.com/dotnet/arcade/pull/4373
> Update post-build stages required to push build to latest

- azure-pipelines.yml
Adjusting to latest changes here.
fixes the build break in https://dev.azure.com/dnceng/internal/_build/results?buildId=436515&view=results
> Adjust Push_to_latest_channel dependsOn

- azure-pipelines.yml
- eng/validation/update-channel.ps1
Closes: https://github.com/dotnet/arcade/issues/4677
Use Darc to promote Arcade builds to the final channel.
> Promote Arcade builds using Darc

- azure-pipelines.yml
- eng/validation/update-channel.ps1
Test / Success validation here: https://dnceng.visualstudio.com/internal/_build/results?buildId=526646&view=results
> Fix call to Darc add-build-to-channel

- azure-pipelines.yml
- eng/validation/build-arcadewithrepo.ps1
Arcade Validation pipeline that this ran on: https://dev.azure.com/dnceng/internal/_build/results?buildId=619603&view=results
> Add Installer to Arcade Validation pipeline

- eng/validation/build-arcadewithrepo.ps1
A lot of failures in repos have been due to timeouts and are generally resolved by re-running the failed stages, however, that means we still don't validate against them. We're changing this to report on non-green repos, however, we'll still create a branch and kick off a pipeline run of that branch in the event that the parent code is actually green, but is failing due to timeouts.
> Always run on bellwether repos

- eng/validation/build-arcadewithrepo.ps1
fixes https://github.com/dotnet/arcade/issues/6075
`git commit -am` does not include new files. so run a git add beforehand.
Test build (that will also serve as a promotion validation for today): https://dnceng.visualstudio.com/internal/_build/results?buildId=794933&view=results
> Add all files in working tree before commiting

- azure-pipelines.yml
- eng/Publishing.props
- eng/validation/test-publishing.ps1
V3 publishing for arcade-validation 
with default channel =>https://dnceng.visualstudio.com/internal/_build/results?buildId=821061&view=results
without default channel => https://dnceng.visualstudio.com/internal/_build/results?buildId=820168&view=results
> V3 publishing 

- eng/validation/validation-functions.ps1
https://github.com/dotnet/core-eng/issues/12212
Queued https://dnceng.visualstudio.com/internal/_build/results?buildId=998599&view=logs&j=bd570bf9-4a66-5807-2b10-d7a24a0f00a3 to demonstrate it works
> Setting core.longpaths to tolerate > 260 character paths

- azure-pipelines-bellwether-repos.yml
- azure-pipelines.yml
- eng/validation/update-channel.ps1
https://github.com/dotnet/arcade/issues/7119
> m2m renaming

- azure-pipelines-bellwether-repos.yml
- eng/validation/update-channel.ps1
**Note**: Will merge this once Installer has completed their migration.
> Change Installer's branch name from master to main in validation scripts

- azure-pipelines.yml
Related to https://github.com/dotnet/core-eng/issues/12816
> Skip component governance detection where not needed

- eng/validation/test-publishing.ps1
As of the release/5.0 timeframe, all publishing is supposed to be handled by the main arcade branch.  If this works I might need to port to main too, though changes that are merged to main tend to be much closer to main.
Checking with build: https://dev.azure.com/dnceng/internal/_build/results?buildId=1103013&view=results
> Test publishing using arcade main branch

- eng/common/sdk-task.ps1
- eng/common/tools.ps1
https://github.com/dotnet/arcade/issues/7494
> Updated xcopy-msbuild to 16.10.0-preview2 to fix signing issue

- eng/validation/update-channel.ps1
Update promotion channel for release/6.0 branch 
Issue -> https://github.com/dotnet/arcade/issues/7818
Also updated the channels
> Update promotion channel

- eng/validation/update-channel.ps1
Get-AzDO-Build function is never called, so removing it.
> Remove unused function

- azure-pipelines.yml
- eng/validation/update-channel.ps1
Release/6.0 branch should be used instead of main to promote to .Net 6 Eng Channel
> Use release/6.0 branch to promote to .Net 6 Eng Channel

- azure-pipelines.yml
> Use 1ES hosted pools

- azure-pipelines.yml
Tracking issue: https://github.com/dotnet/core-eng/issues/14276
> [release/6.0] Migrate to 1ES hosted pools

- azure-pipelines-bellwether-repos.yml
- azure-pipelines.yml
- clean-up-branches.yml
Also , update 1ES images to match VS version
> Update hosted windows agents to 2019 for impending end-of-life

- azure-pipelines.yml
https://github.com/dotnet/core-eng/issues/14783 (it's defaulting to Windows 2017)
> Specify pool for Promote_arcade_to_latest 

- azure-pipelines.yml
Fixes official build failure: https://dev.azure.com/dnceng/internal/_build/results?buildId=1587939&view=logs&j=cbd85b09-5d6a-5129-5e64-9957f65551fe&t=afda548f-998b-5648-e342-41d846471293&l=31
> use powershell core for update-channel.ps1

- azure-pipelines.yml
> Switch to new images

- azure-pipelines.yml
fixes bug introduced in https://github.com/dotnet/arcade-validation/pull/3355
> [release/6.0] fix the yaml typo for pr builds

- azure-pipelines.yml
- global.json
- src/Validation/tests/RepoTests.cs
- src/Validation/tests/TestRepoBuilder.cs
The update should work some time next week.
> Revert arcade update and test workaround made earlier

- azure-pipelines.yml
Switch to new images on release/3.x.
> [release/3.x] Switch to new images

- eng/Versions.props
- src/Validation/tests/Validation.Tests.csproj
> Bump some package versions

- eng/Versions.props
- src/Validation/tests/Validation.Tests.csproj
- see https://github.com/dotnet/dnceng/issues/566
> [release/6.0] Restore NewtonSoft.Json direct dependency

- azure-pipelines.yml
Update pool provider usage for new branch: https://github.com/dotnet/arcade/issues/14068
> Update all pool provider usage to -Svc version (branching for release) 

- azure-pipelines.yml
https://github.com/dotnet/arcade/issues/14068
> Update branch to promote builds to .NET 8 Eng

- azure-pipelines.yml
- eng/common/templates/job/execute-sdl.yml
- eng/common/templates/job/onelocbuild.yml
- eng/common/templates/job/publish-build-assets.yml
- eng/common/templates/job/source-index-stage1.yml
- eng/common/templates/post-build/post-build.yml
- eng/common/templates/variables/pool-providers.yml
Attempt to resolve CI failures: https://github.com/dotnet/dnceng/issues/904
> Update build agents from VS2019 to VS2022

- azure-pipelines-pr.yml
- azure-pipelines.yml
Split azure pipeline into two files, one for CI and one for PR, starting creating the one for pr :) 
Issue: https://github.com/dotnet/dnceng/issues/2178
Validated in build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=600600&view=results
> [1ES Template] Create azure-pipeline-pr.yaml file 

- azure-pipelines-pr.yml
Split azure pipeline into two files, one for CI and one for PR, starting creating the one for pr :)
Issue: https://github.com/dotnet/dnceng/issues/2178
Validated in build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=600969&view=results
> [release/8.0][1ES Template] Create azure-pipeline-pr.yaml file

- azure-pipelines.yml
Migrating main branch
Pipeline migrated: https://dev.azure.com/dnceng/internal/_build?definitionId=282&_a=summary
Tested in build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2401976&view=results
> [main][1ES Template] Migrate ci pipeline

- azure-pipelines-pr.yml
Split azure pipeline into two files, one for CI and one for PR, starting creating the one for pr :)
Issue: https://github.com/dotnet/dnceng/issues/2178
Build validation: https://dev.azure.com/dnceng-public/public/_build/results?buildId=602471&view=results
> [release/6.0][1ES Template] Create azure-pipeline-pr.yaml template

- azure-pipelines.yml
Migrating release/6.0 branch
Pipeline migrated: https://dev.azure.com/dnceng/internal/_build?definitionId=282&_a=summary
Tested in build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2403749&view=results
> [release/6.0][1ES Template] Migrate ci pipeline

- azure-pipelines-pr.yml
build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=607168&view=results
issue: https://github.com/dotnet/dnceng/issues/2178
> [release/7.0][1ES Template] Create azure-pipeline-pr.yml

- azure-pipelines-pr.yml
- azure-pipelines.yml
I notice Windows 10. Should that be updated to Windows 11?
> Update Debian version in `main`

- azure-pipelines.yml
Migrating release/8.0 branch
Pipeline migrated: https://dev.azure.com/dnceng/internal/_build?definitionId=282&_a=summary
Tested in build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2410330&view=results
> [release/8.0][1ES Template] Migrate ci pipeline

- azure-pipelines.yml
Migrating release/7.0 branch
Pipeline migrated: https://dev.azure.com/dnceng/internal/_build?definitionId=282&_a=summary
Tested in build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2412153&view=results
> [release/7.0][1ES Template] Migrate pipele of arcade-validation-official

- azure-pipelines-pr.yml
- azure-pipelines.yml
https://github.com/dotnet/arcade/issues/14622
Updates windows 10 queue
> [Release/8.0] Update windows 10 testing queue

- azure-pipelines.yml
Fixes https://github.com/dotnet/dnceng/issues/3013
> Use new Maestro URI

- eng/create-baridtag.ps1
Fixes https://github.com/dotnet/dnceng/issues/3028
> Fix build tag creation

- eng/create-baridtag.ps1
This changes with today's rollout
> Use `darc --ci`

- azure-pipelines.yml
> [release 9.0] Use servicing build pools

- azure-pipelines.yml
- eng/create-baridtag.ps1
- eng/validation/test-publishing.ps1
- eng/validation/update-channel.ps1
Validation: https://dev.azure.com/dnceng/internal/_build/results?buildId=2634005&view=results
> Update to new Darc authentication

- azure-pipelines.yml
> Fix update-channel arguments

- azure-pipelines.yml
- eng/create-baridtag.ps1
- eng/validation/test-publishing.ps1
- eng/validation/update-channel.ps1
ports https://github.com/dotnet/arcade-validation/pull/4779
> Fix darc auth release/9.0

- azure-pipelines.yml
Related to https://github.com/dotnet/dnceng/issues/5264
Working with MicroBuild engineer to get this diagnosed. He asked that we increase the timeout to see what happens/potentially get more information from the logs.
> Increase timeout to 10 minutes

- azure-pipelines.yml
- eng/validation/update-channel.ps1
This PR addresses the issue that prevents the promotion of Arcade to the .Net 6 channel.
> updated script for arcade promotion into .net 6

- eng/Versions.props
- src/Validation/tests/RepoTests.cs
- src/Validation/tests/Validation.Tests.csproj
https://github.com/dotnet/dnceng/issues/5405
> Use AwesomeAssertions instead of FluentAssertions

- eng/create-baridtag.ps1
Fixes "Create BAR ID Tag" failing in arcade-validation build
Looks like this should be made dynamic: https://github.com/dotnet/arcade-validation/pull/4538 😄
> [release/10.0] Update source channel name in script
