dotnet/arcade-validation

eng/validation/update-channel.ps1

This will be the last step we run in the validation build and will add the build(s) which generated the Arcade SDK version we've just validated to the "Latest" channel

Adding update-channel.ps1

---

NuGet.config

Causes CI / official build failures trying to restore a bootstrap-1 version of the Arcade SDK.

Remove arcade nuget package feed

---

NuGet.config
global.json

Attempt to fix what's described in https://github.com/NuGet/Home/issues/7654
/cc: @mmitche (as fyi)

Use the same dotnet cli version and NuGet.config as arcade

---

azure-pipelines.yml
eng/validation/templates/testing/helix.yml

We now do the send_to_helix job in both PR and official builds.
PR job uses anonymous mode, Official build uses authenticated mode.
fixes dotnet/arcade#1641

Use open queues during PR, non-open during official build.

---

eng/Versions.props

This seems to be the cause of nuget incorrectly restoring the wrong arcade SDK version.
Internal builds using this change haven't failed so far, but I want to test this using the external flow as well.

Add nuget version to Versions.props (TEST)

---

azure-pipelines.yml

Sending to Helix is broken without setting this parameter first.

add default for helix access token

---

azure-pipelines.yml

Temporary workaround. This should allow us to keep validating newer Arcade builds, but we won't push them to the channel where other repos would consume from.
@markwilkie @jcagme @mmitche

Disable push to latest channel

---

azure-pipelines.yml

Get us out of the over-used windows.10.amd64/open queue.

Use serverRS4 queue instead of windows.10.amd64 for Helix validation

---

NuGet.config

Relates to: https://github.com/dotnet/arcade/issues/2085
Arcade soon will publish only to arcade-validation feed. This PR makes the eventual new packages available for arcade-validation builds.
Further details: Arcade-validation will add Arcade's build to another channel and that will cause the dotnet-core feed to be updated.

Update list of package sources

---

azure-pipelines.yml

Fixes https://github.com/dotnet/arcade/issues/2971
* Stop using the int pool provider
* The Validate_Signing and SDL jobs are now part of the jobs collection from the jobs.yml templates, so that they are required to succeed before the publish to BAR job.
* The push to 'latest' channel job now only depends only on the publish to BAR job.

Fixes for arcade validation build

---

azure-pipelines.yml

Remove BinSkim from arcade-validation builds as it takes an hour to finish and does not make sense to be run with every build. 
https://github.com/dotnet/core-eng/issues/6550

Remove BinSkim from arcade-validation builds

---

azure-pipelines.yml

Remove fxcop from the sourceToolsList since it's been causing arcade-validation builds to time out, and is blocking the flow of new versions of the arcade sdk.
https://dev.azure.com/dnceng/internal/_build/results?buildId=215785
The fxcop run is full of errors like:
```
FxCop completed with exit code 9
Error running FxCop job: 1 of 3828
FxCop completed with an Error exit code: 9. An analysis error (possibly assembly load error) occurred.
```
and 
```
FxCop completed with exit code 1
Error running FxCop job: 3 of 3828
FxCop completed with an Error exit code: 1. A fatal error occurred. Some of the possible conditions that are considered fatal errors: 1) The analysis could not be performed because of insufficient input. 2) The analysis threw an exception that is not handled by FxCopCmd. 3) …
```

remove fxcop since it's full of errors and timing out

---

azure-pipelines.yml

New variable was introduced in https://github.com/dotnet/arcade/pull/3402 and since Arcade-validation publishes to the validation channel, it needs to set it.

Add new variable since we publish to validation channel

---

azure-pipelines.yml

Without this the CI build runs for every pushed branch ever.

Add proper CI trigger to azure-pipelines.yml

---

azure-pipelines.yml
eng/common/templates/post-build/post-build.yml

Fixes the gap outlined in: https://github.com/dotnet/arcade/issues/3982
Test build incoming once the fix for the arcade templates makes it to the latest channel but want to get early feedback on the approach.

move copy-to-latest-channel to its own stage

---

azure-pipelines.yml
eng/validation/update-channel.ps1

Release/3.x version of https://github.com/dotnet/arcade-validation/pull/866
fixes https://github.com/dotnet/arcade/issues/3982
Test build: https://dev.azure.com/dnceng/internal/_build/results?buildId=361873&view=results

move Push Build to '.NET Tools 3' channel to its own stage

---

azure-pipelines.yml

Build is broken because the stage `Push_to_latest_channel` has a dependency on the deleted stage `NetCore_Dev30_Publish`. The stage/channel implementation was removed in Arcade in this PR: https://github.com/dotnet/arcade/pull/3967

Fix build - Remove dependency on deleted stage

---

NuGet.config

This caused a problem when recently arcade stopped publishing to dotnet-tools because of an issue with the order a change should have been made. https://github.com/dotnet/arcade/pull/4117
Because arcade-validation was in this nuget.config, this problem was not caught immediately, and only seen when arcade was ingested into itself.

Remove blob feed from nuget.config

---

eng/common/post-build/setup-maestro-vars.ps1

resurrected the file by running a darc update-dependencies --channel ".NET 3 Tools - Validation"
Looking into this as part of dotnet/arcade#4193
Will unblock the official build.

Add back script deleted by dependency update PR

---

NuGet.config

I'll merge this once Arcade-validation is broken by the dependency update from https://github.com/dotnet/arcade/pull/4279
That will let us make sure the channel and feed configurations are still correct with the initial change.

use dotnet-eng feed to react to feed change

---

azure-pipelines.yml

The parameter has already been added to the public and internal pipelines.

Use PoolProvider, supplied as a queue-time parameter

---

azure-pipelines.yml

We'd like to make sure that our staging machines are healthy, so this change adds a scheduled build that uses the staging pool provider instead of prod.

Add Scheduled job using Staging Pool Provider

---

azure-pipelines.yml

The PAT currently in use is a developer PAT. Changing to a dn-bot owned PAT.
Tested this locally and the new PAT is able to queue the promotion builds.

Use dn-bot account to trigger promotion pipeline

---

azure-pipelines.yml

Closes: #https://github.com/dotnet/arcade/issues/4963
- Remove deprecated properties.
- Disable Windows debug leg for internal builds.
Tested here:
- https://dnceng.visualstudio.com/internal/_build/results?buildId=545932&view=results
- https://dnceng.visualstudio.com/internal/_build/results?buildId=545912&view=results
- https://dnceng.visualstudio.com/internal/_build/results?buildId=545738&view=results

Some refactoring in build-def YAML

---

azure-pipelines.yml
eng/validation/build-arcadewithrepo.ps1

Other things done in this PR: 
- Removing Roslyn from validation process (they're no longer taking in Arcade via the Latest channel)
- Look up builds on specific branches
- Include manual builds in LKG look-up
Test run of the pipeline with these changes here: https://dnceng.visualstudio.com/internal/_build/results?buildId=583675&view=results

Adding ASPNETCore repo to Arcade Validation

---

azure-pipelines.yml
eng/validation/build-arcadewithrepo.ps1

Verified with this run that a partiallySucceeded build in ASPNETCore was used for the LKG build: https://dnceng.visualstudio.com/internal/_build/results?buildId=608639&view=logs&j=bd570bf9-4a66-5807-2b10-d7a24a0f00a3
This was the SHA: ab0a422154d42835a215db5c74ea325b75bab6c4
Which relates back to: https://dev.azure.com/dnceng/internal/_build/results?buildId=607928&view=results

LKGs should include "partiallySucceeded" builds, too

---

azure-pipelines.yml
eng/validation/build-arcadewithrepo.ps1

We'll use the Latest Build endpoint from AzDO's API to determine if we should validate Arcade against the repo. If the Latest Build result is "partiallySucceeded" or "succeeded", then we'll use the SHA of that build to build Arcade with in that repo. If the result is "cancelled" or "failed", then we won't validate Arcade with that repo.

Arcade Validation should only look at product repo latest builds instead of LKGs

---

azure-pipelines.yml
eng/validation/test-publishing.ps1

This adds a stage to Arcade Validation to publish itself to General Testing channel, in order to test publishing. 
Validated here: https://dnceng.visualstudio.com/internal/_build/results?buildId=703497&view=logs&j=56ebfe15-69d8-5dd1-65e4-c65998c8d8a6&t=0a9483a6-3ac1-5fd2-c450-3586b050b65b

Including 'Validate Publishing' stage

---

src/Validation/tests/Validation.Tests.csproj

This is preparation for when we update the version of the Microsoft.NET.Test.Sdk in Arcade. Part of https://github.com/dotnet/arcade/issues/5291

Stop producing package for Validation.Tests

---

NuGet.config
azure-pipelines.yml

https://github.com/dotnet/arcade/issues/5788 and some validation for https://github.com/dotnet/arcade/issues/5890
* Add build steps to run the SetupNugetSources scripts in linux and windows builds.
* Add a fake source that the scripts should not re-enable as it will cause nuget to die
* Add a real source that the logs should show is re-enabled.
Some additional validation to make sure the nuget.config file looks as expected should be added to complete the validation.
Test build: https://dnceng.visualstudio.com/internal/_build/results?buildId=758611&view=results

Add Setup private feeds credentials during official build stage

---

NuGet.config
azure-pipelines.yml

dotnet/arcade#5788 and some validation for dotnet/arcade#5890 for the release/3.x branch
Add build steps to run the SetupNugetSources scripts in linux and windows builds.
Add a fake source that the scripts should not re-enable as it will cause nuget to die
Add a real source that the logs should show is re-enabled.
Clean up the nuget.config
Test build: https://dnceng.visualstudio.com/internal/_build/results?buildId=758685&view=results
The errors in the windows release configuration are due to missing the fix from https://github.com/dotnet/arcade/pull/5897

Use SetupNugetSources scripts during official build 

---

azure-pipelines.yml

This will prevent issues when validating private arcade versions.
https://github.com/dotnet/arcade/issues/6313
Test build: https://dnceng.visualstudio.com/internal/_build/results?buildId=847354&view=results

Only do validate_publishing if the branch being built is master

---

azure-pipelines.yml
eng/validation/update-channel.ps1

https://github.com/dotnet/arcade/issues/6390
This change makes it so the official build will promote the arcade build to the .net 5 eng channel automatically.
It takes advantage of the --skip-assets-publishing flag because we don't need to republish any assets.
I also ported the change from https://github.com/dotnet/arcade-validation/pull/1869 so that private builds of the release/5.0 branch don't do the "validate publishing" stage.
Test build (this added the missing build to the channel even) https://dnceng.visualstudio.com/internal/_build/results?buildId=849418&view=results

Promote build automatically to .net 5 eng

---

azure-pipelines.yml

Now that we have completed dotnet/core-eng#11006 we need to change the names of the queues to allow Helix redirect arcade jobs

Use queue name to allow helix redirect

---

azure-pipelines.yml

Part of dotnet/core-eng#11446
Now that Helix redirects work based on the repository we have to change the queue names

Remove .Arcade from Helix queue names

---

azure-pipelines-bellwether-repos.yml
azure-pipelines.yml
clean-up-branches.yml

See https://github.com/dotnet/core-eng/issues/11993
It woudl appear the Installer repo ends up indirectly cloning repos from devdiv.vs now.  
Since we have a PAT that works for both projects .NET Core development runs in, may as well use that for all as any repo could do this in the future.

Switch to using a PAT that works for both dnceng and devdiv

---

eng/validation/build-arcadewithrepo.ps1
eng/validation/test-publishing.ps1
eng/validation/validation-functions.ps1

Since this isn't necessarily indicative of anything wrong, just print warning and exit.  Also print output when we have git errors.
https://github.com/dotnet/core-eng/issues/11993

Handle scenario of no darc updates for a given repo

---

azure-pipelines.yml
eng/validation/test-publishing.ps1

See https://github.com/dotnet/core-eng/issues/12258 for context.  
We are trying not to have dnceng/internal cloning from Github directly, and the pipeline this validation script uses is now explicitly mapped to dnceng/internal. 
@mmitche FYI.
Validated using [this build](https://dnceng.visualstudio.com/internal/_build/results?buildId=1003654&view=logs&s=0d7db6e4-c533-50c8-77c7-b1b9fc049ed6), including making sure that the val/... branch got deleted.

Move promotion pipeline repo from github to Azure Devops

---

eng/validation/update-channel.ps1

The logging functions require $ci to be $true. Setting this variable causes the lines to output with the necessary vso headers

Fix logging for validation

---

Directory.Build.props
azure-pipelines.yml

This is https://github.com/dotnet/arcade/issues/3069 again, I recreated it because deleting the comment wasn't rendering properly so I made a new branch on my fork.

Fix source linking in arcade-validation, and reenable source link validation

---

src/Validation/tests/RepoTests.cs

Add a few tests for this feature, which replaces Microsoft400 with MicrosoftDotNet500 when the flag is set. Defaults to false.
Ensure that this works on two paths:
- Post build signing
- Regular signing
Necessary to have tests for both these cases because the places where the certificate replacement is different for PBS and in-build signing

Add tests exercising UseDotNetCertificate

---

azure-pipelines.yml

https://github.com/dotnet/dotnet-docker/issues/2848 - dockerhub images are now delisted.  This moves to mcr.microsoft.com version.

Update docker image source

---

azure-pipelines.yml

By default we were using NetCorePublic-Pool and NetCoreInternal-Pool for internal builds, changing them to be 1ES pools

Always use 1ES Pools

---

azure-pipelines.yml

Staging CloudTest images have `-Int` suffix but we forgot to take it into account when migrating the pipeline. Also we need to increase max scale on staging pools. This PR temporarily reverts to the old pools to unblock the promotion.
Issue: https://github.com/dotnet/arcade/issues/7987

Revert "Use R&D pools (#2525)"

---

azure-pipelines.yml

We have renamed staging 1ES images to match production names. Now we can once again apply the migration to 1ES  hosted pools.
Tracking issue: https://github.com/dotnet/arcade/issues/7987

Migrate to 1ES pools

---

azure-pipelines.yml

https://github.com/dotnet/arcade/issues/8368
This used to be a job template. It's now a steps template. Since it runs in the same job, we no longer need the `dependsOn`. 
Validated this works as expected in this test build: https://dev.azure.com/dnceng/internal/_build/results?buildId=1563053&view=results

React to arcade template changes in setup-maestro-vars.yml

---

eng/validation/update-channel.ps1

Followup to https://github.com/dotnet/arcade/issues/8368. I missed that one of my test builds failed in the promotion step.
Powershell's invoke-webRequest has a dependency on Internet Explorer being installed in the machine because of course it does. The useBasicParsing parameter is how you get around that. 
Solves failures such as the one seen here: https://dev.azure.com/dnceng/internal/_build/results?buildId=1563274&view=results

add UseBasicParsing to Invoke-WebRequest calls

---

azure-pipelines.yml

This image isn't having trouble with Image Factory, and should spin up faster.
Mitigates https://github.com/dotnet/arcade/issues/9455

Move to a server-based build image

---

azure-pipelines.yml

Official internal run version: https://dev.azure.com/dnceng/internal/_build/results?buildId=1834538&view=results

Move from impendingly-removed Debian 9 queue to a dockerized Debian 10

---

src/Validation/tests/RepoTests.cs
src/Validation/tests/TestRepoBuilder.cs

If the killing processes logic hit an exception it may not enumerate all processes on the machine, leaving leaked dotnet.exe for the subsequent cleanup step

Small test fix

---

azure-pipelines.yml

Move the build to use the new images. These images have .net 6 installed, which is required for the validate publishing leg to run successfully.
Fixes the official build break in https://github.com/dotnet/arcade/issues/10769
I have a test build of these changes here: https://dev.azure.com/dnceng/internal/_build/results?buildId=1986870&view=results

[Release/6.0] Move to new images that have .net 6 installed 

---

azure-pipelines.yml

This change moves all of the docker images to the -latest tag as part of #10377.

Use latest docker tags

---

azure-pipelines.yml

We changed the latest tags to not include the -latest suffix, so this change updates those tags to the new schema.

Update latest docker tags with new schema

---

azure-pipelines.yml

Had a typo I didn't catch because I merged my last PR too quickly and didn't let the internal test build finish
test build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2013722&view=results
I don't trust myself today so do not let me merge this until that build finishes. Only sending this now to get PR validation that doesn't exercise this going.

[release/5.0] fix build pool name for the validate publishing Job

---

eng/create-baridtag.ps1

Using the bar id itself means that we end up having to directly reference maestro to get all of the comparison builds (we have to go current build -> maestro -> azdo build for that bar id -> compare build -> maestro -> azdo build). Maestro can be clunky and if we can avoid using it, that's better. Since we can just get the azdo url for a given asset/build, we can avoid the code that uses this information needing maestro by just saving the build url

Add tag for Validating AzDO build

---

eng/Versions.props
src/Validation/tests/Validation.Tests.csproj

- see https://github.com/dotnet/dnceng/issues/566
- bump Microsoft.Build to 17.7.0, also the latest package version
- remove unnecessary package references
- transitive references seem sufficient at this time

[main] Bump MSBuild.ProjectCreation to 10.0.0

---

eng/Versions.props
src/Validation/tests/Validation.Tests.csproj

- see https://github.com/dotnet/dnceng/issues/566
- latest version of the package remains `net6.0`-compatible
- also bump Microsoft.Build to 17.3.2, latest `net6.0` package
- remove unnecessary package references
- transitive references seem sufficient at this time

[release/6.0] Bump MSBuild.ProjectCreation to 10.0.0

---

eng/Versions.props
src/Validation/tests/Validation.Tests.csproj

- see https://github.com/dotnet/dnceng/issues/566
- bump Microsoft.Build to 17.7.0, also the latest package version
- remove unnecessary package references
- transitive references seem sufficient at this time

[release/7.0] Bump MSBuild.ProjectCreation to 10.0.0

---

azure-pipelines.yml
eng/create-baridtag.ps1
eng/validation/build-arcadewithrepo.ps1
eng/validation/test-publishing.ps1

Resolves dotnet/dnceng#1964.
The validation checks get confused if an asset with the same name and version is published more than once. This is rare, but can happen. This change adds the source-channel flag where appropriate for calls to `darc`.

Specify source channel for asset validation

---

azure-pipelines.yml

Delete publishing validation stage in release 6.0, because we have use always use main for build  promotion

Delete publishing validation in release 6.0 

---

azure-pipelines-pr.yml
azure-pipelines.yml

https://github.com/dotnet/arcade/issues/14622
Update our windows testing target which previously targeted 2016-datacenter to our 2022-datacenter queue.

Update windows 10 testing target

---

eng/create-baridtag.ps1

Fixes official build failures. The script can't (rightfully) find the builds it's trying to validate as it's trying to use the wrong channel 
https://dev.azure.com/dnceng/internal/_build/results?buildId=2526924&view=logs&j=53ba88cb-b0cf-52fc-0bd4-89a0e9972164&t=39268a59-48a4-5735-6fe3-9378ea4b48e1

fix validation channel name for bar id tagging

---

azure-pipelines-pr.yml

Related to https://github.com/dotnet/arcade/issues/14430 and https://github.com/dotnet/arcade/issues/14431
Validates the changes from https://github.com/dotnet/arcade/pull/15045
Enables dry run signing in Linux PR validation runs.

Enable dry-run signing in Linux PR Validation

---

azure-pipelines-pr.yml
azure-pipelines.yml
src/Validation/src/Validation.csproj

Related to https://github.com/dotnet/arcade/issues/14431
Validates the changes in https://github.com/dotnet/arcade/pull/15104 for Linux (Mac is currently blocked - see https://github.com/dotnet/arcade/issues/14431#issuecomment-2387129090)
[Test pipeline run](https://dev.azure.com/dnceng/internal/_build/results?buildId=2552857&view=results) (internal Microsoft link)

Enable signing on Linux

---

global.json

- see https://github.com/dotnet/dnceng/issues/4204
- not required to build the repo; all code here is C#
- section existed only to validate parallel installation of two native tools
- we now want macOS coverage and `cmake` layout is different on that OS

Remove `native-tools` from global.json

---

azure-pipelines.yml

We should no longer use macos-12 - see https://github.com/actions/runner-images/issues/10721

Use mac latest

---

azure-pipelines-pr.yml
azure-pipelines.yml

Internal builds were not being properly containerized with the 1ES templates. This PR also updates the container from cbl-mariner 2.0 to azurelinux 3.0
Proper containerization is needed to test the validity of the MicroBuild signing plugin tasks.
[Test build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2616847&view=results)

Properly containerize CI/PR builds

---

src/Validation/src/Validation.csproj

We use these OS functions in other repos (runtime, VMR, etc.) as well to calculate the BuildOS.

Fix official build publishing due to duplicate assets

---

azure-pipelines.yml

[Test pipeline run](https://dev.azure.com/dnceng/internal/_build/results?buildId=2651244&view=results)

Add diagnostic logging to mac builds

---

azure-pipelines-pr.yml
azure-pipelines.yml

Related to https://github.com/dotnet/source-build/issues/4793.
MicroBuild install has to run after the repo checkout since it installs to the sources directory by default (see https://github.com/dotnet/arcade/pull/15626/commits/0da7c5f1373544b37fa9ca59d3d79bde9adb7b55). For context, it needs to install to the sources directory because the infra requires .NET 8 during signing.
[Internal test build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2661574&view=results)

Move checkout to presteps

---

azure-pipelines-pr.yml
azure-pipelines.yml

Replacing Ubuntu 18.04 with Ubuntu 22.04, Mariner 2 with Azure Linux 3 and Debian 10 with Debian 12

Removing EOL software

---

azure-pipelines.yml
eng/validation/update-channel.ps1

Arcade-validation is failing to promote Arcade to the .net 6 eng channel as seen from this discussion: [Microsoft.Guardian.Cli CG alert](https://teams.microsoft.com/l/message/19:afba3d1545dd45d7b79f34c1821f6055@thread.skype/1747694727991?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1747694727991&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=First%20Responders&createdTime=1747694727991)
Changes were made to main, 8.0 and 9.0, but 6.0 and 7.0 are still using the old maestro, which causes the promotion step to fail.
This PR addresses the issue to enable 6.0 to use the new maestro

updated script for arcade promotion into .net 6
